controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    neck_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    waist_yaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    wheel_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7

    command_interfaces:
      - position

    state_interfaces:
      - position

right_gripper_controller:
  ros__parameters:
    joint: r_gripper_joint
    goal_tolerance: 0.1

    state_interfaces:
      - position
      - velocity

left_arm_controller:
  ros__parameters:
    joints:
      - l_arm_joint1
      - l_arm_joint2
      - l_arm_joint3
      - l_arm_joint4
      - l_arm_joint5
      - l_arm_joint6
      - l_arm_joint7

    command_interfaces:
      - position

    state_interfaces:
      - position

left_gripper_controller:
  ros__parameters:
    joint: l_gripper_joint
    goal_tolerance: 0.1

    state_interfaces:
      - position
      - velocity

neck_controller:
  ros__parameters:
    joints:
      - neck_yaw_joint
      - neck_pitch_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

waist_yaw_controller:
  ros__parameters:
    joints:
      - waist_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

wheel_controller:
  ros__parameters:
    left_wheel_names : ["base_l_drive_wheel_joint"]
    right_wheel_names: ["base_r_drive_wheel_joint"]

    wheel_separation: 0.200
    wheel_radius: 0.045

    wheel_separation_multiplier  : 1.0
    left_wheel_radius_multiplier : 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate : 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity:  1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity:  1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration:  1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
